const Data = [
  {
    _id: '1',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/controller.png?raw=true',
    name: 'HAVIT HV G-92 Gamepad',
    description:'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
    price: '$120',
    rating: 4.5,
    section: '1',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 4,
    numReviews:23,
    stock: 234,
  },
  {
    _id: '2',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/keybord.png?raw=true',
    name: 'AK-900 Wired Keyboard',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    price: '$300',
    rating: 4,
    section: '1',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 6,
    numReviews:6,
    stock: 1,
  },
  {
    _id: '3',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/monitor.png?raw=true',
    name: 'IPS LCD Gaming Monitor',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    price: '$890',
    rating: 4.5,
    section: '1',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 6,
    numReviews:6,
    stock: 1,
  },

  {
    _id: '4',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/Chiar.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'S-Series Comforte Chair',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: '1',
    category: 'home',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },

  
  {
    _id: '5',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/canon.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'CANON EOS DSLR Camera',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4.5,
    section: 'Explore',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 12,
    numReviews: 9,
    stock: 12,
  },
  
  {
    _id: '6',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/Copa.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Jr. Zoom Soccer Cleats',
    price: '$900',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 5,
    section: 'Explore',
    category: 'sport',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 21,
  },
  
  {
    _id: '7',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/GP11_PRD3%201.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'GP11 Shooter USB Gamepad',
    price: '$80',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4.5,
    section: 'Explore',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 13,
  },
  
  {
    _id: '8',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/JBL_BOOMBOX_.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'S-Series Comforte Chair',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: '1',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
  
  {
    _id: '9',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/New-Mercedes-Benz.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Kids Electric Car',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 5,
    section: 'Explore',
    category: 'baby',
    countInStock: 8,
    numReviews: 122,
    stock: 12,
  },
  
  {
    _id: '10',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/b-black.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Quilted Satin Jacket',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: 'Explore',
    category: 'men',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
  
  {
    _id: '11',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/b-red.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'The north coat',
    price: '$378',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: 'BestSelling',
    category: 'men',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
  
  {
    _id: '12',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/bag.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Gucci duffle bag',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4.5,
    section: 'BestSelling',
    category: 'woman',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
  
  {
    _id: '13',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/book-table.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Small BookSelf',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 5,
    section: 'BestSelling',
    category: 'home',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 122,
  },
  
  {
    _id: '14',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/crema.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Curology Product Set ',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: 'Explore',
    category: 'women',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 134,
  },
  
  {
    _id: '15',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/gammaxx.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'RGB liquid CPU Cooler',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4.5,
    section: 'BestSelling',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 93,
    stock: 14,
  },
  
  {
    _id: '16',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/gucci.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'GUCCI INTENSE OUD EDP',
    price: '$1000',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 5,
    section: '1',
    category: 'men',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
  
  {
    _id: '17',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/ideapad.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'ASUS FHD Gaming Laptop',
    price: '$1190',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: 'Explore',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 239,
    stock: 10,
  },
  
  {
    _id: '18',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/kalonka.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Amazon wireless speakers',
    price: '$1090',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 5,
    section: '1',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 96,
    stock: 1,
  },
  
  {
    _id: '19',
    image: 'https://github.com/Iskender-Garajayev/shop-app/blob/master/public/image/petfood.png?raw=true',
    // image: 'image/Chiar.png',
    name: 'Breed Dry Dog Food',
    price: '$890',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
    rating: 4,
    section: 'Explore',
    category: 'pets',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 1,
  },
  {
    _id: '20',
    image: 'https://raw.githubusercontent.com/Iskender-Garajayev/data/main/img/hero__gnfk5g59t0qe_medium.png',
    image: 'https://raw.githubusercontent.com/Iskender-Garajayev/data/main/img/magic_smart_case__e1xikczc5eoi_medium.jpg',
    name: 'AirPods Max',
    price: '$549',
    description:'AirPods Max combine high-fidelity audio with industry-leading Active Noise Cancellation to deliver an unparalleled listening experience. Each part of their custom-built driver works to produce sound with ultra-low distortion across the audible range. From deep, rich bass to accurate mids and crisp, clean highs, you’ll hear every note with a new sense of clarity.',
    rating: 4.5,
    section: 'Explore',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 200,
  },
  {
    _id: '21',
    image: 'https://raw.githubusercontent.com/Iskender-Garajayev/data/main/img/iphone-compare-iphone-15-pro-202309.jpg',
    image: 'https://raw.githubusercontent.com/Iskender-Garajayev/data/main/img/iphone-15-pro-model-unselect-gallery-2-202309_GEO_US.jpg',
    name: 'iPhone 15 Pro',
    price: '$549',
    description:'iPhone 15 Pro is the first iPhone to feature an aerospace‑grade titanium design, using the same alloy that spacecraft use for missions to Mars.',
    rating: 5 ,
    section: 'Explore',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 200,
  },
  {
    _id: '22',
    image: 'https://raw.githubusercontent.com/Iskender-Garajayev/data/main/img/iphone-compare-iphone-15-pro-202309.jpg',
    name: 'Macbook Pro',
    price: '$549',
    description:'iPhone 15 Pro is the first iPhone to feature an aerospace‑grade titanium design, using the same alloy that spacecraft use for missions to Mars.',
    rating: 5 ,
    section: 'Explore',
    category: 'Electronics',
    color: ['red', 'white'],
    countInStock: 8,
    numReviews: 9,
    stock: 200,
  },

  // {
  //   _id: '19',
  //   image: 'https://www.apple.com/v/iphone-14/h/images/key-features/features/size/size_yellow__dnv9794q7loy_large.jpg',
  //   // image: 'image/Chiar.png',
  //   name: 'Breed Dry Dog Food',
  //   price: '$890',
  //   description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores aliquam veniam debitis deleniti. Soluta, illum.',
  //   rating: 4,
  //   section: 'Explore',
  //   category: 'Electronics',
  //   countInStock: 8,
  //   numReviews: 9,
  //   stock: 1,
  // },
  

]

export default Data